name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/node-devops-app .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USER }}/node-devops-app
           - name: Install AWS CLI
        run: sudo apt-get update && sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      - name: Deploy to EKS 🚀
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name devops-cluster
          kubectl rollout restart deployment node-devops-app
