name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/node-devops-app .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USER }}/node-devops-app
