apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayanraaz12345/node-app.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
